server:
  port: 8080
  servlet:
    context-path: /template

spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=template
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
