server:
  port: 8080
  servlet:
    context-path: /template

spring:
  application:
    name: template
  datasource:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=template
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092

#Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
    instances:
      myCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 20s